n_galaxies: 200
n_iterations: 10
mag_bins: 7
min_mag: 24.0
max_mag: 27.0
z_bins: 9
min_z: 7
max_z: 9
n_bands: 7
ref_uv_wl: 1600
detection_band:
bands:
zeropoints:
gain_values:
det_combination:
coadd_type:
list_of_fields: /Users/nleethochawa/Documents/workspace_UVLF/Run_Glaciar/jwst/list_jwst.txt
R_eff: 1.075
beta_mean: -2.2
beta_sd: 0.4
size_pix: 0.08
margin: 0.3
path_to_images: /Users/nleethochawa/Documents/workspace_UVLF/jwst_mock_data/
path_to_results: /Users/nleethochawa/Documents/workspace_UVLF/Run_Glaciar/jwst/
image_name: borg_
imfits_end: _drz_sci.fits
rmsfits_end: _drz_rms_sclv2.fits
fixed_psf:
types_galaxies: 2
sersic_indices:
- 1
- 4
fraction_type:
- 0.5
- 0.5
ibins: 4
ebins: 4
min_sn: 0
dropouts: True
droptype: borg25
de_Vacouleur: True
LF_shape: ['flat']
lin_slope: 
exp_base:
n_inject_max:
Minput_min: -23.5
Minput_max: -20.0
