n_galaxies: 200
n_iterations: 5
mag_bins: 12
min_mag: 23.0
max_mag: 28.5
z_bins: 1
min_z: 5
max_z: 5
n_bands: 9
ref_uv_wavelength: 1500
detection_band: det
bands:
- f435w
- f606w
- f775w
- f814w
- f850lp
- f105w
- f125w
- f140w
- f160w
zeropoints:
- 25.68
- 26.51
- 25.69
- 25.94
- 24.87
- 26.27
- 26.23
- 26.45
- 25.94
gain_values:
- 1 
- 1 
- 1
- 1
- 1 
- 1
- 1
- 1
- 1
detection_band_combination:
- f160w
- f140w
- f125w
- f850lp
coadd_type: 2
list_of_fields: /Users/nleethochawa/Documents/workspace_UVLF/Run_Glacier/HLF/list.txt
R_eff: 1.075
beta_mean: -2.2
beta_sd: 0.4
size_pix: 0.06
margin: 0.3
path_to_images: /Users/nleethochawa/Documents/workspace_UVLF/CANDELS_data/HLF/
path_to_results: /Users/nleethochawa/Documents/workspace_UVLF/Run_Glacier/HLF/schechter/
image_name: hlsp_hlf_hst_60mas_
imfits_end: _v2.0_conv_sci.fits 
rmsfits_end: _v2.0_conv_wht.fits
fixed_psf: f160w_psf.fits
types_galaxies: 2
sersic_indices:
- 1
- 4
fraction_type_galaxies:
- 0.5
- 0.5
ibins: 5
ebins: 5
min_sn: 3
dropouts: True
droptype: hlf
de_Vacouleur: True
extended_mag_bins_low: 1
extended_mag_bins_high: 1
LF_shape: ['schechter_flat']
lin_slope:
exp_base:
n_inject_max: 1000
